/** @type {import('tailwindcss').Config} */
module.exports = {
    content: [
        "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
        "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
        "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    ],
    theme: {
        extend: {
            container: {
                center: true,
                padding: {
                    DEFAULT: '20px', // Mobile Margin
                    tablet: '30px', // Tablet Margin
                    desktop: '120px', // Desktop Margin
                },
            },
            colors: {
                orange: {
                    50: '#fffaeb',
                    100: '#fff1c5',
                    200: '#ffe485',
                    300: '#ffcf46',
                    400: '#ffb91b',
                    500: '#f08c00',
                    600: '#e26e00',
                    700: '#bb4a02',
                    800: '#983908',
                    900: '#7c2f0b',
                },
                grey: {
                    50: '#f6f6f6',
                    100: '#eeeeee',
                    200: '#e2e2e2',
                    300: '#cbcbcb',
                    400: '#afafaf',
                    500: '#757575',
                    600: '#545454',
                    700: '#333333',
                    800: '#1f1f1f',
                    900: '#141414',
                },
                black: '#000000',
                white: '#ffffff',
                // Semantic Colors
                'red-sale': '#ff2c20',
                'red-600': '#ed2115',
                'green-price': '#00b505',
                'green-700': '#028907',
                'blue-secondary': '#0075ff',
                'blue-info': '#1ea7ff',
                blue: {
                    50: '#e9f4ff',
                    100: '#d6ecff',
                    200: '#b5d9ff',
                    400: '#5b96ff',
                    500: '#356cff',
                    600: '#133fff',
                    700: '#0933f9',
                    800: '#0b2fc8',
                    900: '#13309c',
                    950: '#0e206e',
                },
            },
            fontFamily: {
                sans: ['"Mona Sans"', 'sans-serif'],
                satoshi: ['"Mona Sans"', 'sans-serif'],
                sfpro: ['"Mona Sans"', 'sans-serif'],
                manrope: ['"Mona Sans"', 'sans-serif'],
            },
            fontSize: {
                'xs': ['12px', { lineHeight: '16px', letterSpacing: '-0.4px' }],
                'sm': ['14px', { lineHeight: '20px', letterSpacing: '-0.4px' }],
                'base': ['16px', { lineHeight: '23px', letterSpacing: '-0.4px' }],
                'lg': ['18px', { lineHeight: '25px', letterSpacing: '-0.8px' }],
                'xl': ['21px', { lineHeight: '28px', letterSpacing: '-0.8px' }],
                '2xl': ['27px', { lineHeight: '35px', letterSpacing: '-0.8px' }],
                '3xl': ['36px', { lineHeight: '45px', letterSpacing: '-0.8px' }],
                '4xl': ['47px', { lineHeight: '58px', letterSpacing: '-1.5px' }],
                '5xl': ['62px', { lineHeight: '60px', letterSpacing: '-2.0px' }],
            },
            borderRadius: {
                'none': '0px',
                'sm': '2px',
                DEFAULT: '4px',
                'md': '8px',
                'lg': '12px',
                'xl': '16px',
                '2xl': '20px',
                '3xl': '24px',
                '4xl': '28px',
                '5xl': '32px',
                'full': '9999px',
                'pill': '70px',
            },
            borderWidth: {
                DEFAULT: '1px',
                '0': '0',
                '0.5': '0.5px',
                '1': '1px',
                '1.5': '1.5px',
                '2': '2px',
                '3': '3px',
                '4': '4px',
            },

            screens: {
                'mobile': '390px',
                'tablet': '768px',
                'desktop': '1440px',
            },
            gridTemplateColumns: {
                '12': 'repeat(12, minmax(0, 1fr))',
                '8': 'repeat(8, minmax(0, 1fr))',
                '4': 'repeat(4, minmax(0, 1fr))',
            },
        },
    },
    plugins: [],
}
