import { Manrope, Poppins } from "next/font/google"; // turbo
import "./globals.css";
// ... imports

const manrope = Manrope({
  subsets: ["latin"],
  variable: "--font-manrope",
  display: "swap",
});

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-poppins",
  display: "swap",
});

export const metadata = {
  title: "Indian Rentals",
  description: "Generated by create next app",
};

import { ReduxProvider } from "@/redux/provider";
import ClientLayout from "@/components/ClientLayout";

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${manrope.variable} ${poppins.variable} font-sans bg-gray-50 antialiased overflow-x-hidden max-w-full`}>
        <ReduxProvider>
          <ClientLayout>
            {children}
          </ClientLayout>
        </ReduxProvider>
      </body>
    </html>
  );
}
