'use client';
import { useEffect, useState } from 'react';
import Link from 'next/link';
const API=process.env.NEXT_PUBLIC_API_URL||'http://localhost:5000';
const headers=()=>({Authorization:`Bearer ${localStorage.getItem('adminToken')}`});
const statuses={new:'New',in_progress:'In progress',resolved:'Resolved'};
export default function ContactInbox(){
    const [intent,setIntent]=useState(''),[status,setStatus]=useState(''),[page,setPage]=useState(1),[revision,setRevision]=useState(0),[data,setData]=useState({items:[],total:0}),[loading,setLoading]=useState(true),[error,setError]=useState(''),[saving,setSaving]=useState(''),[unsupported,setUnsupported]=useState(false);
    useEffect(()=>{let active=true;const controller=new AbortController();fetch(`${API}/api/contact/enquiries?${new URLSearchParams({intent,status,page})}`,{headers:headers(),cache:'no-store',signal:controller.signal}).then(async res=>{if(res.status===404){if(active)setUnsupported(true);return;}const body=await res.json();if(!res.ok)throw new Error(body.message||'Unable to load enquiries.');if(active){setData(body);setUnsupported(false);setError('');}}).catch(e=>{if(active&&e.name!=='AbortError')setError(e.message);}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;controller.abort();};},[intent,status,page,revision]);
    async function update(id,nextStatus){setSaving(id);setError('');try{const res=await fetch(`${API}/api/contact/enquiries/${id}`,{method:'PATCH',headers:{...headers(),'Content-Type':'application/json'},body:JSON.stringify({status:nextStatus})});const body=await res.json();if(!res.ok)throw new Error(body.message||'Could not update status.');setRevision(r=>r+1);}catch(e){setError(e.message);}finally{setSaving('');}}
    return <div className="space-y-6"><header className="flex justify-between flex-wrap gap-4"><div><h1 className="text-3xl font-bold">Contact enquiries</h1><p className="text-slate-500 mt-2">Rental and support requests submitted from the contact page.</p></div><Link href="/dashboard/cms/contact" className="underline">Edit contact page</Link></header>{unsupported?<section role="status" className="rounded-2xl border border-amber-300 bg-amber-50 p-6 text-sm text-amber-950"><h2 className="text-lg font-semibold">Enquiry inbox is waiting for the backend update</h2><p className="mt-2 max-w-2xl leading-6">The connected API does not have the contact enquiries endpoint yet. The local contact form cannot submit to this inbox until the updated backend is deployed.</p><button className="mt-4 rounded-full border border-amber-500 px-4 py-2 font-semibold" onClick={()=>{setLoading(true);setRevision(r=>r+1);}}>Check again</button></section>:<><div className="flex flex-wrap items-end gap-4"><label>Request type<select className="block border rounded-lg p-2 mt-1" value={intent} onChange={e=>{setLoading(true);setIntent(e.target.value);setPage(1);}}><option value="">All requests</option><option value="rental">Rental enquiries</option><option value="support">Support requests</option></select></label><label>Status<select className="block border rounded-lg p-2 mt-1" value={status} onChange={e=>{setLoading(true);setStatus(e.target.value);setPage(1);}}><option value="">All statuses</option>{Object.entries(statuses).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label><button className="underline p-2" onClick={()=>{setLoading(true);setRevision(r=>r+1);}}>Refresh</button></div>
        {error&&<p role="alert" className="border border-red-300 rounded-lg p-4">{error}</p>}
        {loading?<p role="status">Loading enquiries…</p>:!error&&<><p className="text-sm text-slate-500">{data.total} requests</p>{data.items.length===0?<p>No requests match these filters.</p>:<div className="space-y-4">{data.items.map(item=><article key={item._id} className="bg-white dark:bg-slate-900 border border-slate-200 rounded-xl p-5 space-y-4"><div className="flex justify-between flex-wrap gap-3"><div><p className="text-sm text-slate-500">{item.intent==='rental'?'Rental enquiry':'Support request'} · {new Date(item.createdAt).toLocaleString()}</p><h2 className="text-xl font-semibold mt-1">{item.fullName}</h2></div><label className="text-sm">Status<select aria-label={`Status for ${item.fullName}`} disabled={!!saving} className="block border p-2 rounded-lg mt-1" value={item.status} onChange={e=>update(item._id,e.target.value)}>{Object.entries(statuses).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label></div><div className="grid sm:grid-cols-2 gap-3 text-sm"><a className="underline break-all" href={`mailto:${item.email}`}>{item.email}</a><a className="underline" href={`tel:${item.phone.replace(/[^+\d]/g,'')}`}>{item.phone}</a><p>City: {item.cityName}</p><p>{item.intent==='rental'?`Equipment: ${item.equipment}`:`Order reference: ${item.order||'Not provided'}`}</p></div><p className="whitespace-pre-wrap break-words">{item.message||'No additional message.'}</p><p className="text-xs text-slate-500 break-all">Reference: {item.submissionId} · Privacy consent recorded</p></article>)}</div>}<div className="flex gap-4 items-center"><button disabled={page===1} onClick={()=>setPage(p=>p-1)} className="border rounded-lg px-4 py-2 disabled:opacity-40">Previous</button><span>Page {page} of {Math.max(1,Math.ceil(data.total/25))}</span><button disabled={page*25>=data.total} onClick={()=>setPage(p=>p+1)} className="border rounded-lg px-4 py-2 disabled:opacity-40">Next</button></div></>}
    </>}</div>;
}
