'use client';
import { useCallback, useEffect, useState } from 'react';
import Link from 'next/link';
import ImageUploader from '@/components/ImageUploader';
const API = process.env.NEXT_PUBLIC_API_URL || 'http://localhost:5000';
const STOREFRONT = (process.env.NEXT_PUBLIC_STOREFRONT_URL || (process.env.NODE_ENV === 'production' ? 'https://indianrenters.com' : 'http://localhost:3000')).replace(/\/$/, '');
const imagePreview = value => value?.startsWith('/') ? `${STOREFRONT}${value}` : value;
const control = 'mt-1 block w-full rounded-lg border border-slate-300 dark:border-slate-600 bg-white dark:bg-slate-900 p-3 text-sm';
const card = 'rounded-xl border border-slate-200 dark:border-slate-700 bg-white dark:bg-slate-900 p-5 space-y-4';
function Field({label,value,onChange,multiline=false,type='text'}) { return <label className="block text-sm font-medium">{label}{multiline?<textarea className={control} rows={3} value={value??''} onChange={e=>onChange(e.target.value)}/>:<input className={control} type={type} value={value??''} onChange={e=>onChange(e.target.value)}/>}</label>; }
const groups = [
    ['Introduction',[['title','Main heading'],['titleAccent','Underlined heading line'],['intro','Introduction',true],['introClosing','Closing line']]],
    ['Contact desk',[['contactTitle','Heading',true],['contactDescription','Description',true],['callLabel','Phone link label'],['phone','Phone number'],['emailLabel','Email link label'],['email','Email address'],['hours','Opening hours',true],['branchLinkLabel','Branch directory link label']]],
    ['Rental & support forms',[['rentalTitle','Rental heading'],['rentalIntro','Rental introduction'],['rentalButton','Rental submit button'],['supportTitle','Support heading'],['supportIntro','Support introduction'],['supportButton','Support submit button'],['successTitle','Confirmation heading'],['successMessage','Confirmation message',true]]],
    ['Branch directory',[['branchesTitle','Heading',true],['branchesIntro','Introduction',true]]],
    ['Help section',[['helpTitle','Heading'],['helpDescription','Description',true]]],
];
export default function ContactCMSPage() {
    const [data,setData]=useState(null),[meta,setMeta]=useState({}),[error,setError]=useState(''),[saved,setSaved]=useState(false),[saving,setSaving]=useState(false);
    const load=useCallback(async()=>{setError('');try{const res=await fetch(`${API}/api/cms/contact`,{cache:'no-store'});const body=await res.json();if(!res.ok||!body.contactContent)throw new Error('Unable to load contact content. Check that the updated backend is running.');setData(body.contactContent);setMeta({metaTitle:body.metaTitle||'',metaDescription:body.metaDescription||''});}catch(e){setError(e.message);}},[]);
    useEffect(()=>{load();},[load]);
    const set=(key,value)=>{setData(d=>({...d,[key]:value}));setSaved(false);};
    async function save(e){e.preventDefault();setSaving(true);setError('');setSaved(false);try{const res=await fetch(`${API}/api/cms/contact`,{method:'PUT',headers:{'Content-Type':'application/json',Authorization:`Bearer ${localStorage.getItem('adminToken')}`},body:JSON.stringify({contactContent:data,...meta})});const body=await res.json();if(!res.ok)throw new Error(body.message||'Could not save contact page.');setData(body.contactContent);setSaved(true);}catch(e){setError(e.message);}finally{setSaving(false);}}
    if(!data)return <div className="p-6">{error?<><p role="alert">{error}</p><button className="mt-4 underline" onClick={load}>Retry</button></>:<p>Loading contact editor…</p>}</div>;
    return <form onSubmit={save} className="space-y-6 pb-16">
        <header className="flex flex-wrap justify-between gap-4"><div><h1 className="text-3xl font-bold">Contact page</h1><p className="text-sm text-slate-500 mt-2">Manage the live contact page. The original design remains at /contact-demo.</p></div><div className="flex gap-4 items-center"><Link href="/dashboard/cms/contact/messages" className="underline">Enquiry inbox</Link><button disabled={saving} className="rounded-lg bg-indigo-600 text-white px-5 py-3 disabled:opacity-50">{saving?'Saving…':'Save changes'}</button></div></header>
        {error&&<p role="alert" className="p-4 border border-red-300 rounded-lg">{error}</p>}{saved&&<p role="status" className="p-4 border border-green-300 rounded-lg">Contact page saved.</p>}
        <fieldset disabled={saving} className="grid grid-cols-1 xl:grid-cols-2 gap-6">
            <section className={card}><h2 className="text-lg font-semibold">Hero image</h2><p className="text-sm text-slate-500">The first section of the page. Image dimensions stay fixed by the responsive template.</p><ImageUploader label="Hero image" existingUrl={imagePreview(data.heroImage)} onUpload={url=>set('heroImage',url)}/><Field label="Image URL" value={data.heroImage} onChange={v=>set('heroImage',v)}/><Field label="Image description" value={data.heroAlt} onChange={v=>set('heroAlt',v)}/><Field label="Text over image" value={data.heroTitle} onChange={v=>set('heroTitle',v)}/><label className="flex gap-3 items-center"><input type="checkbox" checked={data.heroShowText} onChange={e=>set('heroShowText',e.target.checked)}/>Show text over image</label><Field label="Section background colour" type="color" value={data.heroBackground} onChange={v=>set('heroBackground',v)}/><Field label="Background hex value" value={data.heroBackground} onChange={v=>set('heroBackground',v)}/></section>
            {groups.map(([title,fields])=><section className={card} key={title}><h2 className="text-lg font-semibold">{title}</h2>{fields.map(([key,label,multiline])=><Field key={key} label={label} multiline={multiline} value={data[key]} onChange={value=>set(key,value)}/>)}{title==='Rental & support forms'&&<Field label="Equipment options (one per line)" multiline value={data.equipment.join('\n')} onChange={value=>set('equipment',value.split('\n'))}/>}</section>)}
            <section className={card}><h2 className="text-lg font-semibold">Help links</h2>{data.helpLinks.map((link,index)=><div className="space-y-3 border-b pb-4" key={index}><Field label={`Link ${index+1} label`} value={link.label} onChange={label=>set('helpLinks',data.helpLinks.map((l,i)=>i===index?{...l,label}:l))}/><Field label="Destination" value={link.href} onChange={href=>set('helpLinks',data.helpLinks.map((l,i)=>i===index?{...l,href}:l))}/></div>)}</section>
            <section className={card}><h2 className="text-lg font-semibold">Search appearance</h2><Field label="Page title" value={meta.metaTitle} onChange={metaTitle=>{setMeta(m=>({...m,metaTitle}));setSaved(false);}}/><Field label="Meta description" multiline value={meta.metaDescription} onChange={metaDescription=>{setMeta(m=>({...m,metaDescription}));setSaved(false);}}/></section>
            <section className={`${card} xl:col-span-2`}><h2 className="text-lg font-semibold">Cities and branches</h2><p className="text-sm text-slate-500">These details also populate the form’s city choices. Keep service cities distinct from physical branches. Rotation advances every 3 seconds, with pause and manual selection controls.</p><div className="grid grid-cols-1 lg:grid-cols-2 gap-5">{data.branches.map((branch,index)=>{const update=(key,value)=>set('branches',data.branches.map((b,i)=>i===index?{...b,[key]:value}:b));return <details key={branch.id} className="rounded-lg border border-slate-200 p-4"><summary className="font-semibold cursor-pointer">{branch.name}</summary><div className="space-y-4 pt-4"><Field label="City name" value={branch.name} onChange={v=>update('name',v)}/><label className="block text-sm">Location type<select className={control} value={branch.type} onChange={e=>update('type',e.target.value)}>{['Head office','Branch office','Service city'].map(type=><option key={type}>{type}</option>)}</select></label><Field label="Address" multiline value={branch.address} onChange={v=>update('address',v)}/><Field label="Service city description" multiline value={branch.serviceNote} onChange={v=>update('serviceNote',v)}/><Field label="Phone" value={branch.phone} onChange={v=>update('phone',v)}/><Field label="Directions URL" value={branch.mapUrl} onChange={v=>update('mapUrl',v)}/><ImageUploader label={`${branch.name} illustration`} existingUrl={imagePreview(branch.image)} onUpload={url=>update('image',url)}/><Field label="Illustration URL" value={branch.image} onChange={v=>update('image',v)}/></div></details>;})}</div></section>
        </fieldset>
    </form>;
}
